version: '2'
services:
    sampleapp-mysql:
        container_name: sampleapp-mysql
        image: mysql:5.7.14
        # volumes:
        #     - ~/volumes/jhipster/sampleapp/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=sampleapp
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
